import {
  Alert,
  Badge,
  Button,
  Card,
  Col,
  Collapse,
  CollapsePanel,
  Descriptions,
  DescriptionsItem,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Form,
  FormItem,
  Image,
  Input,
  InputNumber,
  InputPassword,
  Layout,
  LayoutContent,
  LayoutHeader,
  List,
  ListItem,
  ListItemMeta,
  Menu,
  MenuDivider,
  MenuItem,
  Modal,
  Popconfirm,
  Popover,
  Result,
  Row,
  Select,
  SelectOption,
  Segmented,
  Space,
  Spin,
  Steps,
  Switch,
  TabPane,
  Table,
  Tabs,
  Tag,
  Textarea,
  Tooltip,
  TypographyParagraph,
  TypographyText,
  TypographyTitle,
  Upload,
} from 'ant-design-vue'

const components = {
  'a-alert': Alert,
  'a-badge': Badge,
  'a-button': Button,
  'a-card': Card,
  'a-col': Col,
  'a-collapse': Collapse,
  'a-collapse-panel': CollapsePanel,
  'a-descriptions': Descriptions,
  'a-descriptions-item': DescriptionsItem,
  'a-divider': Divider,
  'a-drawer': Drawer,
  'a-dropdown': Dropdown,
  'a-empty': Empty,
  'a-form': Form,
  'a-form-item': FormItem,
  'a-image': Image,
  'a-input': Input,
  'a-input-number': InputNumber,
  'a-input-password': InputPassword,
  'a-layout': Layout,
  'a-layout-content': LayoutContent,
  'a-layout-header': LayoutHeader,
  'a-list': List,
  'a-list-item': ListItem,
  'a-list-item-meta': ListItemMeta,
  'a-menu': Menu,
  'a-menu-divider': MenuDivider,
  'a-menu-item': MenuItem,
  'a-modal': Modal,
  'a-popconfirm': Popconfirm,
  'a-popover': Popover,
  'a-result': Result,
  'a-row': Row,
  'a-select': Select,
  'a-select-option': SelectOption,
  'a-segmented': Segmented,
  'a-space': Space,
  'a-spin': Spin,
  'a-steps': Steps,
  'a-switch': Switch,
  'a-tab-pane': TabPane,
  'a-table': Table,
  'a-tabs': Tabs,
  'a-tag': Tag,
  'a-textarea': Textarea,
  'a-tooltip': Tooltip,
  'a-typography-paragraph': TypographyParagraph,
  'a-typography-text': TypographyText,
  'a-typography-title': TypographyTitle,
  'a-upload': Upload,
}

export function registerAntdComponents(app) {
  for (const [name, component] of Object.entries(components)) {
    app.component(name, component)
  }
  return app
}
